language: node_js
node_js: node
script: npm run build
deploy:
- provider: script
  script: scripts/deploy.sh
  on:
    repo: ComplexCurves/website
    branch: vue
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_dd6f69ac9b09_key -iv $encrypted_dd6f69ac9b09_iv -in .travis/github_deploy_key.enc -out .travis/github_deploy_key -d
