language: node_js
node_js: node
script: npm run build
before_deploy:
- scripts/before_deploy.sh
deploy:
  provider: pages
  local_dir: deploy
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  fqdn: complexcurves.org
  on:
    branch: master
